spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/library
    username: admin
    password: admin123
    driverClassName: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
      show-sql: true
      # format_sql: true
      # properties:
      #   hibernate.format_sql: true
      #   hibernate.type: trace
    properties:
      hibernate:
        jdbc:
          time_zone: UTC

security:
  jwt:
    secret-key: verysecretkeyohmygodwhyitissohardtobreak

