# Datasource configuration
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/library
    username: admin
    password: admin123
    driverClassName: org.postgresql.Driver

  # JPA configuration
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
      show-sql: true
      format-sql: true  # Enabled for readable SQL logs
    properties:
      hibernate:
        jdbc:
          time_zone: UTC

# Security configuration
security:
  jwt:
    secret-key: verysecretkeyohmygodwhyitissohardtobreak

# Logging configuration
logging:
  level:
    root: INFO  # Default log level for other packages
    org.hibernate.SQL: DEBUG  # Log SQL queries
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE  # Log SQL parameter bindings
    org.springframework.security: DEBUG  # Debug Spring Security
    com.h2: DEBUG  # Debug for your application package
  file:
    name: logs/app.log  # Log file location
    max-size: 10MB  # Maximum size before rotation
    max-history: 30  # Keep 30 days of log history
    total-size-cap: 3GB  # Total size cap for all log files